### PR TITLE
Create online transpiler 

### PR DESCRIPTION
**Pull request by tsuchikazu**
ref https://github.com/juliankrispel/decaf/issues/76

I tried create online transpiler. 

`scripts/decaf.js` is created by following command in my local pc, manually... :(
```sh
git checkout master
browserify src/parser.js -t babelify --standalone decaf --outfile dist/decaf.js
git checkout gh-pages
cp dist/decaf.js scripts/decaf.js
```

### CODE REVIEW

**Comment by eventualbuddha** [comment]
I recommend adding a script to `master` that updates this branch automatically. Otherwise it gets out of sync with the released version pretty quickly. See https://github.com/decaffeinate/decaffeinate/blob/master/script/update-gh-pages.sh

**Comment by juliankrispel** [comment]
excellent advice thanks @eventualbuddha @tsuchikazu can you add that?

**Comment by tsuchikazu** [comment]
@eventualbuddha 
That's great! thank you!!!

@juliankrispel 
I’ll give it a try.

**Comment by juliankrispel** [comment]
thanks @tsuchikazu

**Pull request merged**
